<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>iscexport</string>
	</array>
	<key>name</key>
	<string>Export</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#cos-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#description</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sqlquery</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#prolog</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#any-tag</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>any-attr</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.source.iscexport</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.source.iscexport</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Za-z0-9]+)\s*(=)\s*(\".*?\")</string>
		</dict>
		<key>any-tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#start-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#end-tag</string>
				</dict>
			</array>
		</dict>
		<key>cos-block</key>
		<dict>
			<key>begin</key>
			<string>(\&lt;)(Routine|Implementation).*?(\&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.iscexport</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&lt;/)(Routine|Implementation)(\&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.iscexport</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\&lt;\!\[CDATA\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.source.iscexport</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\]\]\&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.source.iscexport</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.isc.cos</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>description</key>
		<dict>
			<key>begin</key>
			<string>(\&lt;)(Description)(\&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.iscexport</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&lt;/)(Description)(\&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.iscexport</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.documentation.source.iscexport</string>
		</dict>
		<key>end-tag</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.iscexport</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\&lt;/)([A-Za-z0-9]+)(\&gt;)</string>
		</dict>
		<key>prolog</key>
		<dict>
			<key>begin</key>
			<string>\&lt;\?</string>
			<key>end</key>
			<string>\?\&gt;</string>
			<key>name</key>
			<string>comment.line.source.iscexport</string>
		</dict>
		<key>sqlquery</key>
		<dict>
			<key>begin</key>
			<string>(\&lt;)(SqlQuery)(\&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.iscexport</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&lt;/)(SqlQuery)(\&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.iscexport</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.isc.cos</string>
				</dict>
			</array>
		</dict>
		<key>start-tag</key>
		<dict>
			<key>begin</key>
			<string>(\&lt;)([A-Za-z0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.iscexport</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.iscexport</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#any-attr</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.iscexport</string>
	<key>uuid</key>
	<string>c3ffa455-1218-4e6f-877f-e6a234279d76</string>
</dict>
</plist>
