<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cls</string>
	</array>
	<key>firstLineMatch</key>
	<string>\s*((?i)Include|Class|///)</string>
	<key>name</key>
	<string>Caché Class</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#include-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#field-comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class-definition</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>Class Block</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#field-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#index-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fk-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>/* */ comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.isc.udl}</string>
		</dict>
		<key>block-cos</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>Cache ObjectScript block</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cos</string>
				</dict>
			</array>
		</dict>
		<key>block-js</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>Javascript method body</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#js</string>
				</dict>
			</array>
		</dict>
		<key>block-sql</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>SQL Query block</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<key>block-xml</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>is this an XData block?</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#xdata-style</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<key>class-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Class)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Class Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>illegal.invalid.source.isc.udl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyword-extends</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>clientmethod-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)ClientMethod)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ClientMethod Definition Line</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generic-method-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-js</string>
				</dict>
			</array>
		</dict>
		<key>cos</key>
		<dict>
			<key>comment</key>
			<string>COS syntax highlighting</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-cos</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.isc.cos</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>cosmethod-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)ClassMethod|Method|Trigger)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Method/ClassMethod Definition Line</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generic-method-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-cos</string>
				</dict>
			</array>
		</dict>
		<key>field-comment</key>
		<dict>
			<key>comment</key>
			<string>Field comments (triple slash)</string>
			<key>match</key>
			<string>^\s*///.*$</string>
			<key>name</key>
			<string>comment.block.documentation.source.isc.udl</string>
		</dict>
		<key>fk-definition</key>
		<dict>
			<key>begin</key>
			<string>\s*(ForeignKey)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Foriegn Key Definition Line</string>
			<key>end</key>
			<string>\s*;\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s\b</string>
					<key>end</key>
					<string>\s</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#fk-type</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b((?i)References)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.source.isc.udl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\[|;|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#fk-type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>fk-type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.source.isc.udl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%|\b)([A-Za-z0-9]*)\(([A-Za-z\%][A-Za-z0-9]*)\)</string>
		</dict>
		<key>generic-method-definition</key>
		<dict>
			<key>begin</key>
			<string>\G\s*([A-Za-z%][A-Za-z0-9]*)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Generic Method Definition Line (name, parameters, return type and attributes)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method-parameter-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-as</string>
				</dict>
			</array>
		</dict>
		<key>include-directive</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Include)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>#include directive</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-name-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>index-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Index)\s+([A-Z-a-z%][A-Za-z0-9.]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Index Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-on</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</array>
		</dict>
		<key>index-field</key>
		<dict>
			<key>comment</key>
			<false/>
		</dict>
		<key>js</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-js</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>keyword-as</key>
		<dict>
			<key>begin</key>
			<string>\b((?i)As)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>As &lt;type&gt;</string>
			<key>end</key>
			<string>(?=\[|;|=|,|\)|$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>keyword-extends</key>
		<dict>
			<key>begin</key>
			<string>\b((?i)Extends)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Extends Classname</string>
			<key>end</key>
			<string>(?=\[)|$</string>
			<key>name</key>
			<string>keyword.operator.source.isc.udl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-name-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>keyword-on</key>
		<dict>
			<key>begin</key>
			<string>\b((?i)On)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;index&gt; On &lt;field-list&gt;</string>
			<key>end</key>
			<string>(?=\[|;)|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-name-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.source.isc.udl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.source.isc.udl</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>index on collection</string>
					<key>match</key>
					<string>\((KEYS)\)|\((ELEMENTS)\)</string>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</array>
		</dict>
		<key>line-comment</key>
		<dict>
			<key>comment</key>
			<string>//comment</string>
			<key>match</key>
			<string>^\s*//.*</string>
			<key>name</key>
			<string>comment.line.double-slash.source.isc.udl</string>
		</dict>
		<key>member-attr</key>
		<dict>
			<key>begin</key>
			<string>(\[|\G)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>attr=value</string>
			<key>end</key>
			<string>(,|\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(=)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.isc.udl</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>attr value</string>
					<key>end</key>
					<string>(?=,|\s|\])|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#value-string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#value-literal</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#sql-expression</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[A-Za-z_][A-Za-z0-9_]+</string>
							<key>name</key>
							<string>entity.type.name.source.isc.udl</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>attr name</string>
					<key>match</key>
					<string>\b[A-Za-z][A-Za-z0-9 ]+\b</string>
					<key>name</key>
					<string>storage.modifier.source.isc.udl</string>
				</dict>
			</array>
		</dict>
		<key>member-attr-list</key>
		<dict>
			<key>begin</key>
			<string>(?=\[)</string>
			<key>comment</key>
			<array>
				<string>attr=value</string>
			</array>
			<key>end</key>
			<string>(?&lt;=\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr</string>
				</dict>
			</array>
		</dict>
		<key>member-name</key>
		<dict>
			<key>comment</key>
			<string>&lt;member name&gt;</string>
			<key>match</key>
			<string>(\b|%)([A-Za-z][A-Za-z0-9]*)\b</string>
			<key>name</key>
			<string>entity.name.type.source.isc.udl</string>
		</dict>
		<key>member-name-list</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>comment</key>
			<string>(&lt;type1&gt;,&lt;type2&gt;)</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>keyword.operator.source.isc.udl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
			</array>
		</dict>
		<key>method-block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>Method Block</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-xml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-sql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-cos</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-js</string>
				</dict>
			</array>
		</dict>
		<key>method-definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#query-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#clientmethod-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cosmethod-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xdata-definition</string>
				</dict>
			</array>
		</dict>
		<key>method-parameter</key>
		<dict>
			<key>begin</key>
			<string>(\(|\G)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;parm&gt; As &lt;type&gt;=&lt;value&gt;</string>
			<key>end</key>
			<string>(\))|(,)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
			</array>
		</dict>
		<key>method-parameter-list</key>
		<dict>
			<key>begin</key>
			<string>(?=\()</string>
			<key>comment</key>
			<string>method (&lt;parms&gt;,&lt;parm&gt;)</string>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#method-parameter</string>
				</dict>
			</array>
		</dict>
		<key>parameter-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Parameter)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type..source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parameter Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</array>
		</dict>
		<key>parameter-value</key>
		<dict>
			<key>begin</key>
			<string>(=)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;parm&gt;=&lt;value&gt;</string>
			<key>end</key>
			<string>(?=,|;|\s|\))|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value-expression</string>
				</dict>
			</array>
		</dict>
		<key>property-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Property|Relationship)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Property Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</array>
		</dict>
		<key>query-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Query)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Query Definition Line</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generic-method-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-sql</string>
				</dict>
			</array>
		</dict>
		<key>sql-expression</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>SQLComputeCode, RetrievalCode, etc.</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>variable.source.isc.udl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>([A-Za-z_%][A-Za-z0-9_]*)|(\*)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>type-attr</key>
		<dict>
			<key>begin</key>
			<string>([A-Za-z]+)\s*((=)\s*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.isc.udl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\,|\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>type-attr-list</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>name</key>
			<string>keyword.operator.source.isc.udl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-attr</string>
				</dict>
			</array>
		</dict>
		<key>type-name</key>
		<dict>
			<key>comment</key>
			<string>&lt;class name&gt;</string>
			<key>match</key>
			<string>(\b|%)([A-Za-z][A-Za-z0-9.]*)\b</string>
			<key>name</key>
			<string>entity.name.type.source.isc.udl</string>
		</dict>
		<key>type-name-list</key>
		<dict>
			<key>begin</key>
			<string>\s\(</string>
			<key>comment</key>
			<string>(&lt;type1&gt;,&lt;type2&gt;)</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>keyword.operator.source.isc.udl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>value-expression</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>{&lt;expression&gt;}</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cos</string>
				</dict>
			</array>
		</dict>
		<key>value-literal</key>
		<dict>
			<key>comment</key>
			<string>numeric constant</string>
			<key>match</key>
			<string>([0-9]+\.?[0-9]*)|(\.[0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.source.isc.udl</string>
		</dict>
		<key>value-string</key>
		<dict>
			<key>comment</key>
			<string>quoted string</string>
			<key>match</key>
			<string>(\".*?\")+</string>
			<key>name</key>
			<string>string.quoted.double.source.isc.udl</string>
		</dict>
		<key>xdata-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)XData)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ClientMethod Definition Line</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#xdata-definition-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-xml</string>
				</dict>
			</array>
		</dict>
		<key>xdata-definition-line</key>
		<dict>
			<key>begin</key>
			<string>\G\s*([A-Za-z%][A-Za-z0-9]*)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
			</array>
		</dict>
		<key>xdata-style</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\&lt;style type=\"text/css\"\&gt;)</string>
			<key>comment</key>
			<string>XData Style block for inline ZEN CSS</string>
			<key>end</key>
			<string>(?=\&lt;/style\&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.source.isc.udl</string>
	<key>uuid</key>
	<string>12faaa2e-31d0-4e2c-8c31-a91770a45a8c</string>
</dict>
</plist>
