<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cls</string>
	</array>
	<key>firstLineMatch</key>
	<string>\s*((?i)Include|Class|///)</string>
	<key>name</key>
	<string>Caché Class</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#include-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#field-comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class-definition</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>Class Block</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#field-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xdata-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#index-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fk-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>/* */ comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.isc.udl}</string>
		</dict>
		<key>block-cos</key>
		<dict>
			<key>begin</key>
			<string>\G\s+(?=((?i)SET|S|KILL|K|DO|D|GOTO|G|WRITE|W|READ|R|OPEN|O|USE|U|IF|I|ELSE|E|WHILE|FOR|F|CONTINUE|QUIT|Q|HALT|H|XECUTE|X|ZWRITE|ZW|ZZDUMP|ZKILL|ZK|New|\$\$\$|#|;|//|/\*))</string>
			<key>comment</key>
			<string>Cache ObjectScript block</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cos</string>
				</dict>
			</array>
		</dict>
		<key>block-js</key>
		<dict>
			<key>begin</key>
			<string>^</string>
			<key>comment</key>
			<string>is this a ClientMethod block?</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>block-sql</key>
		<dict>
			<key>begin</key>
			<string>\G\s*(?=((?i)SELECT|UPDATE|CREATE|DELETE|DROP|INSERT|ALTER))</string>
			<key>comment</key>
			<string>is this a Query block?</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<key>block-xml</key>
		<dict>
			<key>begin</key>
			<string>\G\s*(?=&lt;.*&gt;)</string>
			<key>comment</key>
			<string>is this an XData block?</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<key>class-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Class)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Class Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-extends</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>cos</key>
		<dict>
			<key>comment</key>
			<string>COS syntax highlighting</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.isc.cos</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>cos-syntax</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>placeholder for source.isc.cos</string>
			<key>match</key>
			<string>\b((?i)SET|S|KILL|K|DO|D|GOTO|G|WRITE|W|READ|R|OPEN|O|USE|U|IF|I|ELSE|E|WHILE|FOR|F|CONTINUE|QUIT|Q|HALT|H|XECUTE|X|ZWRITE|ZW|ZZDUMP|ZKILL|ZK)\b</string>
		</dict>
		<key>field-comment</key>
		<dict>
			<key>comment</key>
			<string>Field comments (triple slash)</string>
			<key>match</key>
			<string>^\s*///.*$</string>
			<key>name</key>
			<string>comment.block.documentation.source.isc.udl</string>
		</dict>
		<key>fk-definition</key>
		<dict>
			<key>comment</key>
			<string>Foriegn Key Definition Line</string>
		</dict>
		<key>include-directive</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Include)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>#include directive</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-name-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>index-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Index)\s+([A-Z-a-z%][A-Za-z0-9.]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Index Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-on</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</array>
		</dict>
		<key>keyword-as</key>
		<dict>
			<key>begin</key>
			<string>\b((?i)As)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>As &lt;type&gt;</string>
			<key>end</key>
			<string>(?=\[|;|=|\))|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>keyword-extends</key>
		<dict>
			<key>begin</key>
			<string>\b((?i)Extends)\b</string>
			<key>comment</key>
			<string>Extends Classname</string>
			<key>end</key>
			<string>(?=\[)|$</string>
			<key>name</key>
			<string>keyword.operator.source.isc.udl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-name-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>keyword-on</key>
		<dict>
			<key>begin</key>
			<string>\b((?i)On)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;index&gt; On &lt;field-list&gt;</string>
			<key>end</key>
			<string>(?=\[|;)|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-name-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>line-comment</key>
		<dict>
			<key>comment</key>
			<string>//comment</string>
			<key>match</key>
			<string>^\s*//.*</string>
			<key>name</key>
			<string>comment.line.double-slash.source.isc.udl</string>
		</dict>
		<key>member-attr</key>
		<dict>
			<key>begin</key>
			<string>(\G|\[)</string>
			<key>comment</key>
			<string>attr=value</string>
			<key>end</key>
			<string>(,|\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(=)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.isc.udl</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>attr value</string>
					<key>end</key>
					<string>(?=,|\s|\])|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#value-string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#value-literal</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#value-expression</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[A-Za-z_][A-Za-z0-9_]+</string>
							<key>name</key>
							<string>entity.type.name.source.isc.udl</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>attr name</string>
					<key>match</key>
					<string>\b[A-Za-z][A-Za-z0-9 ]+\b</string>
					<key>name</key>
					<string>storage.modifier.source.isc.udl</string>
				</dict>
			</array>
		</dict>
		<key>member-attr-list</key>
		<dict>
			<key>begin</key>
			<string>(?=\[)</string>
			<key>comment</key>
			<string>[attr=value]</string>
			<key>end</key>
			<string>(?&lt;=\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr</string>
				</dict>
			</array>
		</dict>
		<key>member-name</key>
		<dict>
			<key>comment</key>
			<string>&lt;member name&gt;</string>
			<key>match</key>
			<string>(\b|%)([A-Za-z][A-Za-z0-9]*)\b</string>
			<key>name</key>
			<string>entity.name.type.source.isc.udl</string>
		</dict>
		<key>member-name-list</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>comment</key>
			<string>(&lt;type1&gt;,&lt;type2&gt;)</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>keyword.operator.source.isc.udl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
			</array>
		</dict>
		<key>method-block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>Method Block</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-xml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-sql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-cos</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-js</string>
				</dict>
			</array>
		</dict>
		<key>method-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Method|Trigger|ClassMethod|ClientMethod|Query)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Method Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method-parameter-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
			</array>
		</dict>
		<key>method-parameter</key>
		<dict>
			<key>begin</key>
			<string>(\(|\G)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;parm&gt; As &lt;type&gt;=&lt;value&gt;</string>
			<key>end</key>
			<string>(\))|(,)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
			</array>
		</dict>
		<key>method-parameter-list</key>
		<dict>
			<key>begin</key>
			<string>(?=\()</string>
			<key>comment</key>
			<string>method (&lt;parms&gt;,&lt;parm&gt;)</string>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#method-parameter</string>
				</dict>
			</array>
		</dict>
		<key>parameter-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Parameter)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type..source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parameter Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</array>
		</dict>
		<key>parameter-value</key>
		<dict>
			<key>begin</key>
			<string>(=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>&lt;parm&gt;=&lt;value&gt;</string>
			<key>end</key>
			<string>(?=,|;|\s|\))|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value-expression</string>
				</dict>
			</array>
		</dict>
		<key>property-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)Property|Relationship)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Property Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword-as</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>keyword.operator.source.isc.udl</string>
				</dict>
			</array>
		</dict>
		<key>type-attr-list</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>comment</key>
			<string>As &lt;Type&gt;(&lt;PARM&gt;=&lt;VALUE&gt;)</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>keyword.operator.source.isc.udl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.source.isc.udl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.isc.udl</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.type.name.source.isc.udl</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.source.isc.udl</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.source.isc.udl</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.source.isc.udl</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>attr=value</string>
					<key>match</key>
					<string>([A-Za-z]+)\s*((=)\s*(([A-Za-z][A-Za-z0-9]+)|(".*")|(\{.*\})|([0-9.]*)))?(,)?</string>
				</dict>
			</array>
		</dict>
		<key>type-name</key>
		<dict>
			<key>comment</key>
			<string>&lt;class name&gt;</string>
			<key>match</key>
			<string>(\b|%)([A-Za-z][A-Za-z0-9.]*)\b</string>
			<key>name</key>
			<string>entity.name.type.source.isc.udl</string>
		</dict>
		<key>type-name-list</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>comment</key>
			<string>(&lt;type1&gt;,&lt;type2&gt;)</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>keyword.operator.source.isc.udl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type-name</string>
				</dict>
			</array>
		</dict>
		<key>value-expression</key>
		<dict>
			<key>comment</key>
			<string>{&lt;expression}</string>
			<key>match</key>
			<string>\{.*\}</string>
			<key>name</key>
			<string>invalid.illegal.source.isc.udl</string>
		</dict>
		<key>value-literal</key>
		<dict>
			<key>comment</key>
			<string>numeric constant</string>
			<key>match</key>
			<string>([0-9]+\.?[0-9]*)|(\.[0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.source.isc.udl</string>
		</dict>
		<key>value-string</key>
		<dict>
			<key>comment</key>
			<string>quoted string</string>
			<key>match</key>
			<string>\"[^\"]*\"</string>
			<key>name</key>
			<string>string.quoted.double.source.isc.udl</string>
		</dict>
		<key>xdata-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*((?i)XData)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.isc.udl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.source.isc.udl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>XData Definition Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member-attr-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member-name</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.source.isc.udl</string>
	<key>uuid</key>
	<string>12faaa2e-31d0-4e2c-8c31-a91770a45a8c</string>
</dict>
</plist>
